### ISSUE TITLE
Search Results do not appear

### ISSUE THREAD

**Issue by GemmyOrvayne** [chadfurman/tumblr-template-sass#77]
See: http://gaming-thrones.tumblr.com/search/cribs

scroll to bottom

**Comment by ShadeLotus** [comment]
Oh no!

___________

chads.website
LinkedIn <https://linkedin.com/in/chadfurman>
Github <https://github.com/shadelotus>
Twitter <https://twitter.com/chadfurman>
___________

**Comment by GemmyOrvayne** [comment]
I think this is resolved.
